title: Einfach Satt
description: Einfache, gesunde und leckere Rezepte für Gerichte mit wenigen Zutaten. Entdecke eine abwechslungsreiche Ernährung mit proteinreichen Gerichten. Kochen für ein gesundes Leben!
languageCode: de
languageName: Deutsch
displayName: DE
isoCode: de
weight: 1
rtl: false
dateFormat: 2\. January 2006
